@startuml jissyu5_2
actor "ユーザー" as a
boundary "ブラウザ" as b 
control "web.php" as c 
control "jissyu5_1Controller" as d 
boundary "input.blade.php" as e 
boundary "show.blade.php" as f 
boundary "add.blade.php" as g 
boundary "edit.blade.php" as h 
boundary "del.blade.php" as i 
a -> b :該当ページをリクエスト[/jissyu11]
b -> c :GET[/jissyu11]
c -> d :@index
d -> e
a -> e :詳細リンクを押下
c <- e :GET[/jissyu11/show]
c -> d :@show
d -> f 
a -> e :新規登録リンクを押下
c <- e :GET[/jissyu11/add]
c -> d :@add
d -> g 
a -> g :新規登録ボタンを押下
c <- g :POST[/jissyu11/create]
c -> d :@create
d -> e 
a -> e :更新リンクを押下
c <- e :GET[/jissyu11/edit]
c -> d :@edit
d -> h 
a -> h :更新ボタンを押下
c <- h :POST[/jissyu11/update]
c -> d :@update
d -> e 
a -> e :削除リンクを押下
c <- e :GET[/jissyu11/del]
c -> d :@del
d -> i 
a -> i :削除ボタンを押下
c <- i :POST[/jissyu11/remove]
c -> d :@remove
d -> e 
@enduml