@startuml jissyu6_1
actor "ユーザー" as a
boundary "ブラウザ" as b 
control "web.php" as c 
control "jissyu6_1Controller" as d 
entity "Person" as e 
boundary "input.blade.php" as f  
boundary "show.blade.php" as g  
a -> b :該当ページをリクエスト[/jissyu13]
b -> c :GET[/jissyu13]
c -> d :@index
d -> e :all()
d <-- e 
d -> f 
a -> b :検索ボタンを押下
b -> c :GET[/jissyu13]
c -> d :@find
d -> e :where()->first()
d <-- e 
d -> g 
@enduml